/*
 * Project Developed By Jose Daniel Jiménez Medina
 * jdjimenezm@correo.udistrital.edu.co
 */
package vista;

import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jimenez Medina
 */
public class visualizacion extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    DefaultTableModel Modelo;
    checker c;
    
    public visualizacion() {
        
        super ("Cuadro de Actividades");
        c = new checker();
        Modelo = new DefaultTableModel();
        Modelo.addColumn("Nombre");
        Modelo.addColumn("Duración");
        Modelo.addColumn("ID_Actividad");
        Modelo.addColumn("ID_Antecesor");        
        initComponents();   
        this.jTable1.setModel(Modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPtexto = new javax.swing.JPanel();
        JTAtexto = new javax.swing.JTextArea();
        JPbotones = new javax.swing.JPanel();
        JBanadir = new javax.swing.JButton();
        JBdibuja = new javax.swing.JButton();
        JBreiniciar = new javax.swing.JButton();
        JPtabla = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(700, 380));
        setMinimumSize(new java.awt.Dimension(700, 380));
        setPreferredSize(new java.awt.Dimension(700, 380));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JTAtexto.setEditable(false);
        JTAtexto.setBackground(new java.awt.Color(240, 240, 240));
        JTAtexto.setColumns(5);
        JTAtexto.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        JTAtexto.setRows(5);
        JTAtexto.setText("Aquí podrá visualizar las \nactividades registradas, \nlistas para serdibujadas \nen el diagrama de ruta \ncrítica.");
        JTAtexto.setToolTipText("");
        JTAtexto.setAutoscrolls(false);
        JTAtexto.setCaretColor(new java.awt.Color(204, 204, 204));
        JTAtexto.setDisabledTextColor(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout JPtextoLayout = new javax.swing.GroupLayout(JPtexto);
        JPtexto.setLayout(JPtextoLayout);
        JPtextoLayout.setHorizontalGroup(
            JPtextoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPtextoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JTAtexto, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        JPtextoLayout.setVerticalGroup(
            JPtextoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPtextoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JTAtexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(JPtexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 220, 130));

        JPbotones.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        JBanadir.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        JBanadir.setText("Añadir Actividad");
        JBanadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBanadirActionPerformed(evt);
            }
        });

        JBdibuja.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        JBdibuja.setText("Dibujar Diagrama");
        JBdibuja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBdibujaActionPerformed(evt);
            }
        });

        JBreiniciar.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        JBreiniciar.setText("Reiniciar");

        javax.swing.GroupLayout JPbotonesLayout = new javax.swing.GroupLayout(JPbotones);
        JPbotones.setLayout(JPbotonesLayout);
        JPbotonesLayout.setHorizontalGroup(
            JPbotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPbotonesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JPbotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(JBreiniciar, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                    .addGroup(JPbotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(JBdibuja, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                        .addComponent(JBanadir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(11, Short.MAX_VALUE))
        );
        JPbotonesLayout.setVerticalGroup(
            JPbotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPbotonesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JBanadir, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JBdibuja, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JBreiniciar, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(JPbotones, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 171, 220, 160));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout JPtablaLayout = new javax.swing.GroupLayout(JPtabla);
        JPtabla.setLayout(JPtablaLayout);
        JPtablaLayout.setHorizontalGroup(
            JPtablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPtablaLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
        );
        JPtablaLayout.setVerticalGroup(
            JPtablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPtablaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );

        getContentPane().add(JPtabla, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 11, 420, 350));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBanadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBanadirActionPerformed
        // TODO add your handling code here:
          
        configuracion pop = new configuracion(this.Modelo, c);
   
    }//GEN-LAST:event_JBanadirActionPerformed

    private void JBdibujaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBdibujaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JBdibujaActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBanadir;
    private javax.swing.JButton JBdibuja;
    private javax.swing.JButton JBreiniciar;
    private javax.swing.JPanel JPbotones;
    private javax.swing.JPanel JPtabla;
    private javax.swing.JPanel JPtexto;
    private javax.swing.JTextArea JTAtexto;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
